/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTFLoader } from '@react-three/drei/loaders/useGLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTFLoader('/color.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>
        <mesh geometry={nodes['201146'].geometry} material={materials['Default Wall']} />
        <group position={[-10.35, 0.38, 0]} rotation={[0, 0, -Math.PI]} scale={[1, 1, 1]}>
          <mesh geometry={nodes.mesh_1.geometry} material={materials['Aluminum- Klil-Black']} />
          <mesh geometry={nodes.mesh_1_1.geometry} material={materials['Glass-Klil-Clear']} />
        </group>
      </group>
    </group>
  )
}