/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTFLoader } from '@react-three/drei/loaders/useGLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTFLoader('/white.glb')
  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={[1, 1, 1]}>
          <mesh visible={props.showWall} geometry={nodes['201146'].geometry} material={materials['Default Wall']} >
            <meshPhysicalMaterial color={props.wallColor} />
          </mesh>
          <group visible={props.showWindow} position={[-10.35, 0.38, 0]} rotation={[0, 0, -Math.PI]} scale={props.scaleWindow}>
            <mesh geometry={nodes.mesh_1.geometry} material={materials['Aluminum- Klil-Black']} >
              <meshPhongMaterial attach="material" color="red" />
            </mesh>
            <mesh geometry={nodes.mesh_1_1.geometry} material={materials['Glass-Klil-Clear']} >
            </mesh>
          </group>
        </group>
      </group>
    </>
  )
}